# Generated by Django 5.0.6 on 2024-07-04 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=512)),
                ('street', models.CharField(max_length=512)),
                ('zipcode', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=512)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='members.address')),
            ],
        ),
    ]
